// Kernel Function: scope3_incore_0_incore_0_aic
// Generated by PyPTO IR Compiler (PTO backend)

#include <cstdint>
#include <pto/pto-inst.hpp>
#include "tensor.h"

using namespace pto;

#ifndef __gm__
#define __gm__
#endif

#ifndef __aicore__
#define __aicore__ [aicore]
#endif


// --- ptoas-generated code ---

enum class PTOAutoSyncTailMode : int {
  kBarrierAll = 0,
  kSetWaitMte3ToSEvent0 = 1,
};

static __aicore__ inline void ptoas_auto_sync_tail(
    PTOAutoSyncTailMode mode = PTOAutoSyncTailMode::kBarrierAll) {
  switch (mode) {
  case PTOAutoSyncTailMode::kSetWaitMte3ToSEvent0:
    set_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
    wait_flag(PIPE_MTE3, PIPE_S, EVENT_ID0);
    break;
  case PTOAutoSyncTailMode::kBarrierAll:
  default:
    pipe_barrier(PIPE_ALL);
    break;
  }
}


static __aicore__ void scope3_incore_0_incore_0_aic(__gm__ float* v1, __gm__ bfloat16_t* v2, __gm__ float* v3, __gm__ bfloat16_t* v4, int32_t v5) {
  unsigned v6 = 0;
  __gm__ void * v7 = nullptr;
  const int32_t v8 = 128;
  const int32_t v9 = 40;
  const int32_t v10 = 64;
  const int32_t v11 = 8;
  const int32_t v12 = 1;
  const int32_t v13 = 5120;
  const int64_t v14 = 0;
  const int64_t v15 = 16384;
  const int32_t v16 = 0;
  using T = float;

  #if defined(__DAV_CUBE__)
  size_t v17 = (size_t) v12;
  size_t v18 = (size_t) v16;
  auto v19 = TPipe<0, Direction::DIR_BOTH, 4096, 4>(v7, v16, v16);
  set_flag(PIPE_MTE1, PIPE_MTE2, EVENT_ID0);
  set_flag(PIPE_MTE1, PIPE_MTE2, EVENT_ID1);
  set_flag(PIPE_MTE1, PIPE_S, EVENT_ID0);
  set_flag(PIPE_MTE1, PIPE_S, EVENT_ID1);
  set_flag(PIPE_M, PIPE_MTE1, EVENT_ID0);
  set_flag(PIPE_FIX, PIPE_M, EVENT_ID0);
  for (size_t v20 = v18; v20 < ((size_t) v11); v20 += v17) {
    for (size_t v21 = v18; v21 < ((size_t) v9); v21 += v17) {
      Tile<TileType::Mat, bfloat16_t, 128, 64, BLayout::ColMajor, 128, 64, SLayout::RowMajor, 512, PadValue::Null> v22;
      TASSIGN(v22, v15);
      pto::Shape<1, 1, 1, 128, 64> v23 = pto::Shape<1, 1, 1, 128, 64>();
      pto::Stride<655360, 655360, 655360, 5120, 1> v24 = pto::Stride<655360, 655360, 655360, 5120, 1>();
      GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 128, 64>, pto::Stride<655360, 655360, 655360, 5120, 1>, pto::Layout::ND> v25 = GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 128, 64>, pto::Stride<655360, 655360, 655360, 5120, 1>, pto::Layout::ND>(v4 + (v6 + (unsigned) ((int32_t) (uint32_t) ((int32_t) v21) * (uint32_t) v8) * (unsigned) v13 + (unsigned) ((int32_t) (uint32_t) ((int32_t) (uint32_t) ((int32_t) (uint32_t) v5 * (uint32_t) v11) + (uint32_t) ((int32_t) v20)) * (uint32_t) v10) * (unsigned) v12), v23, v24);
      wait_flag(PIPE_MTE1, PIPE_MTE2, EVENT_ID0);
      TLOAD(v22, v25);
      set_flag(PIPE_MTE2, PIPE_MTE1, EVENT_ID0);
      Tile<TileType::Mat, bfloat16_t, 16, 128, BLayout::ColMajor, 16, 128, SLayout::RowMajor, 512, PadValue::Null> v26;
      wait_flag(PIPE_MTE1, PIPE_S, EVENT_ID0);
      TPOP<TPipe<0, Direction::DIR_BOTH, 4096, 4>, Tile<TileType::Mat, bfloat16_t, 16, 128, BLayout::ColMajor, 16, 128, SLayout::RowMajor, 512, PadValue::Null>, TileSplitAxis::TILE_UP_DOWN>(v19, v26);
      set_flag(PIPE_S, PIPE_MTE1, EVENT_ID0);
      Tile<TileType::Left, bfloat16_t, 16, 128, BLayout::ColMajor, 16, 128, SLayout::RowMajor, 512, PadValue::Null> v27;
      TASSIGN(v27, v14);
      wait_flag(PIPE_S, PIPE_MTE1, EVENT_ID0);
      wait_flag(PIPE_M, PIPE_MTE1, EVENT_ID0);
      TMOV(v27, v26);
      set_flag(PIPE_MTE1, PIPE_S, EVENT_ID0);
      TFREE<TPipe<0, Direction::DIR_BOTH, 4096, 4>, TileSplitAxis::TILE_UP_DOWN>(v19);
      Tile<TileType::Right, bfloat16_t, 128, 64, BLayout::RowMajor, 128, 64, SLayout::ColMajor, 512, PadValue::Null> v28;
      TASSIGN(v28, v14);
      wait_flag(PIPE_MTE2, PIPE_MTE1, EVENT_ID0);
      TMOV(v28, v22);
      set_flag(PIPE_MTE1, PIPE_M, EVENT_ID0);
      set_flag(PIPE_MTE1, PIPE_MTE2, EVENT_ID0);
      Tile<TileType::Acc, float, 16, 64, BLayout::ColMajor, 16, 64, SLayout::RowMajor, 1024, PadValue::Null> v29;
      TASSIGN(v29, v14);
      wait_flag(PIPE_MTE1, PIPE_M, EVENT_ID0);
      wait_flag(PIPE_FIX, PIPE_M, EVENT_ID0);
      TMATMUL(v29, v27, v28);
      set_flag(PIPE_M, PIPE_FIX, EVENT_ID0);
      set_flag(PIPE_M, PIPE_MTE1, EVENT_ID0);
      wait_flag(PIPE_M, PIPE_FIX, EVENT_ID0);
      TPUSH<TPipe<0, Direction::DIR_BOTH, 4096, 4>, Tile<TileType::Acc, float, 16, 64, BLayout::ColMajor, 16, 64, SLayout::RowMajor, 1024, PadValue::Null>, TileSplitAxis::TILE_UP_DOWN>(v19, v29);
      set_flag(PIPE_FIX, PIPE_M, EVENT_ID0);
    };
  }
  wait_flag(PIPE_MTE1, PIPE_MTE2, EVENT_ID0);
  wait_flag(PIPE_MTE1, PIPE_MTE2, EVENT_ID1);
  wait_flag(PIPE_MTE1, PIPE_S, EVENT_ID0);
  wait_flag(PIPE_MTE1, PIPE_S, EVENT_ID1);
  wait_flag(PIPE_M, PIPE_MTE1, EVENT_ID0);
  wait_flag(PIPE_FIX, PIPE_M, EVENT_ID0);
  #endif // __DAV_CUBE__

  ptoas_auto_sync_tail(PTOAutoSyncTailMode::kBarrierAll);
  return;
}

static __aicore__ void scope3_incore_0_incore_0_aiv(__gm__ float* v1, __gm__ bfloat16_t* v2, __gm__ float* v3, __gm__ bfloat16_t* v4, int32_t v5) {
  RoundMode v6 = RoundMode::CAST_ROUND;
  unsigned v7 = 0;
  __gm__ void * v8 = nullptr;
  const int64_t v9 = 8;
  const int32_t v10 = 128;
  const int32_t v11 = 40;
  const float v12 = 0.0f;
  const int32_t v13 = 64;
  const int32_t v14 = 8;
  const int32_t v15 = 1;
  const int32_t v16 = 5120;
  const int64_t v17 = 26624;
  const int64_t v18 = 30720;
  const int64_t v19 = 28672;
  const int64_t v20 = 24576;
  const int64_t v21 = 22528;
  const int64_t v22 = 18432;
  const int64_t v23 = 16384;
  const int32_t v24 = 0;
  using T = float;

  #if defined(__DAV_VEC__)
  set_mask_norm();
  set_vector_mask(-1, -1);
  size_t v25 = (size_t) v15;
  size_t v26 = (size_t) v24;
  int64_t v27 = get_subblockid();
  int64_t v28 = (int64_t) v27;
  auto v29 = TPipe<0, Direction::DIR_BOTH, 4096, 4>(v8, v24, v24);
  set_flag(PIPE_MTE3, PIPE_V, EVENT_ID0);
  set_flag(PIPE_MTE3, PIPE_V, EVENT_ID1);
  set_flag(PIPE_V, PIPE_MTE2, EVENT_ID0);
  set_flag(PIPE_V, PIPE_MTE2, EVENT_ID1);
  set_flag(PIPE_MTE3, PIPE_V, EVENT_ID2);
  set_flag(PIPE_MTE3, PIPE_V, EVENT_ID3);
  set_flag(PIPE_V, PIPE_S, EVENT_ID0);
  set_flag(PIPE_V, PIPE_S, EVENT_ID1);
  set_flag(PIPE_V, PIPE_MTE2, EVENT_ID2);
  set_flag(PIPE_V, PIPE_MTE2, EVENT_ID3);
  for (size_t v30 = v26; v30 < ((size_t) v14); v30 += v25) {
    int32_t v31 = (int32_t) ((uint32_t) ((int32_t) (uint32_t) ((int32_t) (uint32_t) v5 * (uint32_t) v14) + (uint32_t) ((int32_t) v30)) * (uint32_t) v13);
    Tile<TileType::Vec, float, 8, 64, BLayout::RowMajor, 8, 64, SLayout::NoneBox, 512, PadValue::Null> v32;
    TASSIGN(v32, v23);
    wait_flag(PIPE_MTE3, PIPE_V, EVENT_ID0);
    TEXPANDS(v32, v12);
    for (size_t v33 = v26; v33 < ((size_t) v11); v33 += v25) {
      Tile<TileType::Vec, float, 8, 128, BLayout::RowMajor, 8, 128, SLayout::NoneBox, 512, PadValue::Null> v34;
      TASSIGN(v34, v22);
      pto::Shape<1, 1, 1, 8, 128> v35 = pto::Shape<1, 1, 1, 8, 128>();
      pto::Stride<40960, 40960, 40960, 5120, 1> v36 = pto::Stride<40960, 40960, 40960, 5120, 1>();
      GlobalTensor<float, pto::Shape<1, 1, 1, 8, 128>, pto::Stride<40960, 40960, 40960, 5120, 1>, pto::Layout::ND> v37 = GlobalTensor<float, pto::Shape<1, 1, 1, 8, 128>, pto::Stride<40960, 40960, 40960, 5120, 1>, pto::Layout::ND>(v1 + (v7 + (unsigned) ((int32_t) (int64_t) ((uint64_t) v28 * (uint64_t) v9)) * (unsigned) v16 + (unsigned) ((int32_t) (uint32_t) ((int32_t) v33) * (uint32_t) v10) * (unsigned) v15), v35, v36);
      wait_flag(PIPE_V, PIPE_MTE2, EVENT_ID0);
      TLOAD(v34, v37);
      set_flag(PIPE_MTE2, PIPE_V, EVENT_ID0);
      Tile<TileType::Vec, bfloat16_t, 8, 128, BLayout::RowMajor, 8, 128, SLayout::NoneBox, 512, PadValue::Null> v38;
      TASSIGN(v38, v21);
      wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID0);
      TCVT(v38, v34, v6);
      set_flag(PIPE_V, PIPE_MTE2, EVENT_ID0);
      Tile<TileType::Vec, bfloat16_t, 8, 128, BLayout::ColMajor, 8, 128, SLayout::RowMajor, 512, PadValue::Null> v39;
      TASSIGN(v39, v20);
      wait_flag(PIPE_MTE3, PIPE_V, EVENT_ID2);
      TMOV(v39, v38);
      set_flag(PIPE_V, PIPE_MTE3, EVENT_ID0);
      wait_flag(PIPE_V, PIPE_MTE3, EVENT_ID0);
      TPUSH<TPipe<0, Direction::DIR_BOTH, 4096, 4>, Tile<TileType::Vec, bfloat16_t, 8, 128, BLayout::ColMajor, 8, 128, SLayout::RowMajor, 512, PadValue::Null>, TileSplitAxis::TILE_UP_DOWN>(v29, v39);
      set_flag(PIPE_MTE3, PIPE_V, EVENT_ID2);
      Tile<TileType::Vec, float, 8, 64, BLayout::RowMajor, 8, 64, SLayout::NoneBox, 512, PadValue::Null> v40;
      wait_flag(PIPE_V, PIPE_S, EVENT_ID0);
      TPOP<TPipe<0, Direction::DIR_BOTH, 4096, 4>, Tile<TileType::Vec, float, 8, 64, BLayout::RowMajor, 8, 64, SLayout::NoneBox, 512, PadValue::Null>, TileSplitAxis::TILE_UP_DOWN>(v29, v40);
      set_flag(PIPE_S, PIPE_V, EVENT_ID0);
      Tile<TileType::Vec, float, 8, 64, BLayout::RowMajor, 8, 64, SLayout::NoneBox, 512, PadValue::Null> v41;
      TASSIGN(v41, v19);
      wait_flag(PIPE_S, PIPE_V, EVENT_ID0);
      TADD(v41, v32, v40);
      set_flag(PIPE_V, PIPE_S, EVENT_ID0);
      TFREE<TPipe<0, Direction::DIR_BOTH, 4096, 4>, TileSplitAxis::TILE_UP_DOWN>(v29);
      Tile<TileType::Vec, float, 8, 64, BLayout::RowMajor, 8, 64, SLayout::NoneBox, 512, PadValue::Null> v42;
      TASSIGN(v42, v23);
      TMOV(v42, v41);
    };
    Tile<TileType::Vec, bfloat16_t, 8, 64, BLayout::RowMajor, 8, 64, SLayout::NoneBox, 512, PadValue::Null> v43;
    TASSIGN(v43, v18);
    int32_t v44 = (int32_t) ((int64_t) (uint64_t) v28 * (uint64_t) v9);
    pto::Shape<1, 1, 1, 8, 64> v45 = pto::Shape<1, 1, 1, 8, 64>();
    pto::Stride<40960, 40960, 40960, 5120, 1> v46 = pto::Stride<40960, 40960, 40960, 5120, 1>();
    GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 8, 64>, pto::Stride<40960, 40960, 40960, 5120, 1>, pto::Layout::ND> v47 = GlobalTensor<bfloat16_t, pto::Shape<1, 1, 1, 8, 64>, pto::Stride<40960, 40960, 40960, 5120, 1>, pto::Layout::ND>(v2 + (v7 + (unsigned) v44 * (unsigned) v16 + (unsigned) v31 * (unsigned) v15), v45, v46);
    wait_flag(PIPE_V, PIPE_MTE2, EVENT_ID2);
    TLOAD(v43, v47);
    set_flag(PIPE_MTE2, PIPE_V, EVENT_ID1);
    Tile<TileType::Vec, float, 8, 64, BLayout::RowMajor, 8, 64, SLayout::NoneBox, 512, PadValue::Null> v48;
    TASSIGN(v48, v17);
    wait_flag(PIPE_MTE2, PIPE_V, EVENT_ID1);
    TCVT(v48, v43, v6);
    set_flag(PIPE_V, PIPE_MTE2, EVENT_ID2);
    Tile<TileType::Vec, float, 8, 64, BLayout::RowMajor, 8, 64, SLayout::NoneBox, 512, PadValue::Null> v49;
    TASSIGN(v49, v23);
    TADD(v49, v32, v48);
    set_flag(PIPE_V, PIPE_MTE3, EVENT_ID1);
    pto::Shape<1, 1, 1, 8, 64> v50 = pto::Shape<1, 1, 1, 8, 64>();
    pto::Stride<40960, 40960, 40960, 5120, 1> v51 = pto::Stride<40960, 40960, 40960, 5120, 1>();
    GlobalTensor<float, pto::Shape<1, 1, 1, 8, 64>, pto::Stride<40960, 40960, 40960, 5120, 1>, pto::Layout::ND> v52 = GlobalTensor<float, pto::Shape<1, 1, 1, 8, 64>, pto::Stride<40960, 40960, 40960, 5120, 1>, pto::Layout::ND>(v3 + (v7 + (unsigned) v44 * (unsigned) v16 + (unsigned) v31 * (unsigned) v15), v50, v51);
    wait_flag(PIPE_V, PIPE_MTE3, EVENT_ID1);
    pipe_barrier(PIPE_MTE3);
    TSTORE(v52, v49);
    set_flag(PIPE_MTE3, PIPE_V, EVENT_ID0);
  }
  wait_flag(PIPE_MTE3, PIPE_V, EVENT_ID0);
  wait_flag(PIPE_MTE3, PIPE_V, EVENT_ID1);
  wait_flag(PIPE_V, PIPE_MTE2, EVENT_ID0);
  wait_flag(PIPE_V, PIPE_MTE2, EVENT_ID1);
  wait_flag(PIPE_MTE3, PIPE_V, EVENT_ID2);
  wait_flag(PIPE_MTE3, PIPE_V, EVENT_ID3);
  wait_flag(PIPE_V, PIPE_S, EVENT_ID0);
  wait_flag(PIPE_V, PIPE_S, EVENT_ID1);
  wait_flag(PIPE_V, PIPE_MTE2, EVENT_ID2);
  wait_flag(PIPE_V, PIPE_MTE2, EVENT_ID3);
  #endif // __DAV_VEC__

  ptoas_auto_sync_tail(PTOAutoSyncTailMode::kBarrierAll);
  return;
}

// --- Kernel entry point ---
extern "C" __aicore__ __attribute__((always_inline)) void kernel_entry(__gm__ int64_t* args)
{
    // Unpack tensor: attn_out__ssa_v0
    __gm__ Tensor* attn_out__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[0]);
    __gm__ float* attn_out__ssa_v0 = reinterpret_cast<__gm__ float*>(attn_out__ssa_v0_tensor->buffer.addr) + attn_out__ssa_v0_tensor->start_offset;

    // Unpack tensor: hidden_states__ssa_v0
    __gm__ Tensor* hidden_states__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[1]);
    __gm__ bfloat16_t* hidden_states__ssa_v0 = reinterpret_cast<__gm__ bfloat16_t*>(hidden_states__ssa_v0_tensor->buffer.addr) + hidden_states__ssa_v0_tensor->start_offset;

    // Unpack tensor: resid1_tile__co_l0_iter_v1
    __gm__ Tensor* resid1_tile__co_l0_iter_v1_tensor = reinterpret_cast<__gm__ Tensor*>(args[2]);
    __gm__ float* resid1_tile__co_l0_iter_v1 = reinterpret_cast<__gm__ float*>(resid1_tile__co_l0_iter_v1_tensor->buffer.addr) + resid1_tile__co_l0_iter_v1_tensor->start_offset;

    // Unpack tensor: wo__ssa_v0
    __gm__ Tensor* wo__ssa_v0_tensor = reinterpret_cast<__gm__ Tensor*>(args[3]);
    __gm__ bfloat16_t* wo__ssa_v0 = reinterpret_cast<__gm__ bfloat16_t*>(wo__ssa_v0_tensor->buffer.addr) + wo__ssa_v0_tensor->start_offset;

    // Unpack scalar: ob__co_idx_v0
    union { uint64_t u64; int64_t val; } ob__co_idx_v0_conv;
    ob__co_idx_v0_conv.u64 = args[4];
    int64_t ob__co_idx_v0 = ob__co_idx_v0_conv.val;

    // Forward to ptoas-generated function
    scope3_incore_0_incore_0_aic(attn_out__ssa_v0, hidden_states__ssa_v0, resid1_tile__co_l0_iter_v1, wo__ssa_v0, ob__co_idx_v0);
}
